#!/bin/bash

echo "🔍 CHECKING AUTH CONFIGURATION"
echo ""
echo "Go to Supabase Dashboard and verify these settings:"
echo ""
echo "1. Authentication → Providers → Google:"
echo "   ✅ Enabled?"
echo "   ✅ Client ID configured?"
echo "   ✅ Client Secret configured?"
echo ""
echo "2. Authentication → URL Configuration:"
echo "   ✅ Site URL: https://japa-genie-test-v1-preauth.vercel.app"
echo "   ✅ Redirect URLs: https://japa-genie-test-v1-preauth.vercel.app/auth/callback"
echo ""
echo "3. Database → Tables → user_profiles:"
echo "   ✅ Table exists?"
echo "   ✅ RLS enabled?"
echo "   ✅ Policies allow INSERT?"
echo ""
echo "4. SQL Editor → Run this query:"
echo ""
echo "SELECT trigger_name FROM information_schema.triggers WHERE trigger_name = 'on_auth_user_created';"
echo ""
echo "Should return: EMPTY (no rows)"
echo ""
