#!/bin/bash

echo "🚀 COMPLETE AUTH & PAYMENT FLOW TEST"
echo "===================================="
echo ""

echo "📊 CHECKING CURRENT SETUP..."
echo "----------------------------"

# Check if all files are in place
check_file() {
  if [ -f "$1" ]; then
    echo "✅ $1"
  else
    echo "❌ $1 - MISSING"
  fi
}

echo ""
echo "📁 ESSENTIAL FILES:"
check_file "src/app/dashboard/page.tsx"
check_file "src/app/api/payment-success/route.ts"
check_file "src/app/api/paystack/create/route.ts"
check_file "src/app/api/create-checkout/route.ts"
check_file "src/app/auth/callback/route.ts"
check_file "src/app/chat/client.tsx"

echo ""
echo "🔍 CHECKING CRITICAL LOGIC:"
echo "- Dashboard protection: $(grep -q "subscriptions" src/app/dashboard/page.tsx && echo "✅" || echo "❌")"
echo "- Payment success handler: $(grep -q "subscriptions" src/app/api/payment-success/route.ts && echo "✅" || echo "❌")"
echo "- Chat bonus wishes: $(grep -q "hasSubscription" src/app/chat/client.tsx && echo "✅" || echo "❌")"

echo ""
echo "🎯 MANUAL TESTING STEPS:"
echo "========================"
echo ""
echo "1. 🆕 NEW USER FLOW TEST:"
echo "   ---------------------"
echo "   a. Go to: http://localhost:3000"
echo "   b. Click 'Start Your Journey'"
echo "   c. Complete KYC form"
echo "   d. EXPECT: Redirect to Chat with '3 wishes left'"
echo "   e. Use 3 chat messages"
echo "   f. EXPECT: 'Choose Plan for Unlimited Access' button appears"
echo "   g. Click pricing button"
echo "   h. EXPECT: Pricing page with 'Continue Your Visa Journey' message"
echo ""

echo "2. 🔄 RETURNING USER (NO PAYMENT) TEST:"
echo "   -----------------------------------"
echo "   a. Log out completely"
echo "   b. Go to: http://localhost:3000"  
echo "   c. Click 'Log In' with Google"
echo "   d. EXPECT: Redirect to Chat with '3 wishes left' (BONUS wishes)"
echo "   e. Use 3 chat messages"
echo "   f. EXPECT: Pricing CTA appears"
echo ""

echo "3. 🛡️ DASHBOARD PROTECTION TEST:"
echo "   -----------------------------"
echo "   a. Try to access: http://localhost:3000/dashboard"
echo "   b. WITHOUT LOGIN: Should redirect to /chat"
echo "   c. WITH LOGIN BUT NO KYC: Should redirect to /kyc"
echo "   d. WITH KYC BUT NO PAYMENT: Should redirect to /pricing"
echo ""

echo "4. 💰 PAYMENT FLOW TEST:"
echo "   --------------------"
echo "   NOTE: Use Stripe test mode for safe testing"
echo "   Test card: 4242 4242 4242 4242"
echo "   "
echo "   a. Go to pricing page"
echo "   b. Choose any plan"
echo "   c. Click 'Get Started'"
echo "   d. Select Stripe payment"
echo "   e. Complete test payment"
echo "   f. EXPECT: Redirect to /dashboard (not /chat)"
echo "   g. Check browser console for: 'Subscription created successfully'"
echo ""

echo "5. 📊 VERIFICATION TESTS:"
echo "   ---------------------"
echo "   a. After payment, check Supabase subscriptions table:"
echo "      SELECT * FROM subscriptions WHERE user_id = 'your-user-id';"
echo "   b. Try accessing /dashboard again - should work now"
echo "   c. Go to chat - should show 'Unlimited wishes'"
echo ""

echo "🔧 TROUBLESHOOTING:"
echo "==================="
echo "❌ Dashboard access denied after payment?"
echo "   - Check browser console for errors"
echo "   - Check server logs for subscription creation"
echo "   - Verify user has record in subscriptions table"
echo ""
echo "❌ Chat not counting bonus wishes?"
echo "   - Check if hasSubscription state is working"
echo "   - Verify user is logged in but has no subscription"
echo ""
echo "❌ Payment success handler not called?"
echo "   - Check payment API success_url is correct"
echo "   - Verify Stripe/Paystack webhook settings"
echo ""

echo "🎉 READY TO TEST!"
echo "Start your dev server: npm run dev"
echo "Then follow the manual testing steps above."
echo ""
echo "💡 PRO TIP: Use different browser/incognito for each test user"
