import InterviewClient from './client';

export default function InterviewPage() {
  return (
    <div className="space-y-8">
      <header className="space-y-2">
        <h1 className="text-4xl font-bold tracking-tight">AI Mock Interview</h1>
        <p className="text-lg text-muted-foreground">
          Prepare for your visa interview with realistic questions generated by AI.
        </p>
      </header>
      <InterviewClient />
    </div>
  );
}
