'use client';

import { useSearchParams } from 'next/navigation';
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { CheckCircle2, XCircle, AlertTriangle, Download, Copy, Check, Sparkles, TrendingUp, MapPin, FileText } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import Link from 'next/link';

export default function EligibilityResultsClient() {
  const searchParams = useSearchParams();
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);

  // Get form data from URL params
  const destination = searchParams.get('destination') || 'your chosen country';
  const visaType = searchParams.get('visaType') || 'Work Visa';
  const background = searchParams.get('background') || '';
  const situation = searchParams.get('situation') || '';

  // Simulated eligibility score (in production, this comes from AI)
  const eligibilityScore = 73; // Example: 73%

  // Simulated recommendations
  const recommendations = [
    { country: 'Canada', score: 85, reason: 'Strong tech sector demand, Express Entry friendly' },
    { country: 'Germany', score: 78, reason: 'EU Blue Card eligibility, no IELTS required' },
    { country: 'Australia', score: 72, reason: 'Points-based system favors your profile' },
  ];

  const strengths = [
    'Work experience aligns with in-demand occupations',
    'Education level meets minimum requirements',
    'Age bracket is favorable for points-based systems',
  ];

  const weaknesses = [
    'Proof of funds may need strengthening',
    'Language test scores could improve your chances',
    'Employer reference letters should be more detailed',
  ];

  const handleCopyResults = () => {
    const resultsText = `
Japa Genie Eligibility Report
━━━━━━━━━━━━━━━━━━━━━━━━━━
Eligibility Score: ${eligibilityScore}%
Destination: ${destination}
Visa Type: ${visaType}

Recommended Countries:
${recommendations.map(r => `• ${r.country} (${r.score}%): ${r.reason}`).join('\n')}

Your Strengths:
${strengths.map(s => `✓ ${s}`).join('\n')}

Areas to Improve:
${weaknesses.map(w => `△ ${w}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Japa Genie - Your AI Visa Assistant
    `.trim();

    navigator.clipboard.writeText(resultsText);
    setCopied(true);
    toast({
      title: 'Copied!',
      description: 'Results copied to clipboard',
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPDF = () => {
    // In production, this would generate a proper PDF
    toast({
      title: 'Download Started',
      description: 'Your PDF report is being generated...',
    });
    // Placeholder: would call backend API to generate PDF
  };

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      {/* Header with Actions */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight">Your Eligibility Report</h1>
          <p className="text-muted-foreground mt-2">Based on your profile for {destination} {visaType}</p>
        </div>
        <div className="flex gap-3">
          <Button onClick={handleCopyResults} variant="outline">
            {copied ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
            {copied ? 'Copied!' : 'Copy Results'}
          </Button>
          <Button onClick={handleDownloadPDF} variant="outline">
            <Download className="mr-2 h-4 w-4" />
            Download PDF
          </Button>
        </div>
      </div>

      {/* Eligibility Score */}
      <Card className="border-2 border-primary/20">
        <CardContent className="pt-6">
          <div className="text-center">
            <div className="inline-flex items-center justify-center w-32 h-32 rounded-full bg-primary/10 mb-4">
              <div className="text-4xl font-bold text-primary">{eligibilityScore}%</div>
            </div>
            <h2 className="text-2xl font-bold mb-2">
              {eligibilityScore >= 75 ? 'Strong Eligibility' : eligibilityScore >= 50 ? 'Moderate Eligibility' : 'Needs Improvement'}
            </h2>
            <p className="text-muted-foreground">
              {eligibilityScore >= 75
                ? 'You have a strong chance of approval with proper documentation'
                : eligibilityScore >= 50
                ? 'You qualify, but strengthening key areas will improve your chances'
                : 'Focus on improving weak areas before applying'}
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Recommended Countries */}
      <div>
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <MapPin className="h-6 w-6 text-primary" />
          Countries That Match Your Profile
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {recommendations.map((rec, index) => (
            <Card key={index} className="border-2 hover:border-primary/50 transition-all">
              <CardHeader>
                <div className="flex items-center justify-between mb-2">
                  <CardTitle className="text-lg">{rec.country}</CardTitle>
                  <span className="text-2xl font-bold text-primary">{rec.score}%</span>
                </div>
                <CardDescription className="text-sm">{rec.reason}</CardDescription>
              </CardHeader>
            </Card>
          ))}
        </div>
      </div>

      {/* Strengths & Weaknesses */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths */}
        <Card className="border-2 border-green-200 bg-green-50/50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-green-700">
              <CheckCircle2 className="h-5 w-5" />
              Your Strengths
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {strengths.map((strength, index) => (
                <li key={index} className="flex items-start gap-2 text-sm">
                  <CheckCircle2 className="h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" />
                  <span>{strength}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {/* Weaknesses */}
        <Card className="border-2 border-amber-200 bg-amber-50/50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-amber-700">
              <AlertTriangle className="h-5 w-5" />
              Areas to Improve
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {weaknesses.map((weakness, index) => (
                <li key={index} className="flex items-start gap-2 text-sm">
                  <AlertTriangle className="h-4 w-4 text-amber-600 mt-0.5 flex-shrink-0" />
                  <span>{weakness}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </div>

      {/* Next Steps */}
      <Card className="border-2 border-primary/20 bg-gradient-to-br from-blue-50 to-purple-50">
        <CardHeader>
          <CardTitle className="text-2xl flex items-center gap-2">
            <TrendingUp className="h-6 w-6 text-primary" />
            Recommended Next Steps
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Button asChild size="lg" className="bg-gradient-to-r from-blue-600 to-primary">
              <Link href="/public-proof-of-funds">
                <FileText className="mr-2 h-5 w-5" />
                Calculate Proof of Funds
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline">
              <Link href="/document-check">
                <Sparkles className="mr-2 h-5 w-5" />
                Check Your Documents
              </Link>
            </Button>
          </div>
          <p className="text-sm text-center text-muted-foreground">
            Need personalized guidance? <Link href="/experts" className="text-primary font-semibold hover:underline">Talk to an expert</Link>
          </p>
        </CardContent>
      </Card>

      {/* Disclaimer */}
      <div className="text-center max-w-2xl mx-auto">
        <p className="text-xs text-muted-foreground">
          ⚠️ This assessment is based on general criteria and your provided information. Final eligibility is determined by immigration authorities. Always verify current requirements on official embassy websites.
        </p>
      </div>
    </div>
  );
}