import { NextResponse } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export const runtime = 'nodejs';

export async function POST(req: Request) {
  try {
    const { letterHTML, analysisResult, targetCountry, visaType } = await req.json();
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]);
    const { width, height } = page.getSize();
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    let y = height - 40;
    const margin = 40;
    const maxWidth = width - 2 * margin;

    // ===== HEADER =====
    page.drawText('JAPA GENIE', { x: margin, y, size: 28, font: fontBold, color: rgb(0.09, 0.32, 0.68) });
    page.drawText('DOCUMENT VERIFICATION REPORT', { x: margin, y: y - 22, size: 10, font: fontRegular, color: rgb(0.4, 0.4, 0.4) });

    // Status badge
    const statusColor = analysisResult.overallStatus === 'pass' ? rgb(0, 0.6, 0) : analysisResult.overallStatus === 'warning' ? rgb(0.9, 0.6, 0) : rgb(0.9, 0, 0);
    page.drawRectangle({ x: width - 180, y: y - 10, width: 140, height: 32, borderColor: statusColor, borderWidth: 2.5, color: rgb(0.95, 0.95, 0.95) });
    page.drawText(analysisResult.overallStatus.toUpperCase(), { x: width - 155, y: y - 1, size: 14, font: fontBold, color: statusColor });
    y -= 65;

    // ===== METADATA BOX =====
    page.drawRectangle({ x: margin, y: y - 45, width: maxWidth, height: 45, color: rgb(0.95, 0.97, 1) });
    page.drawText(`Destination: ${targetCountry} | Visa Type: ${visaType}`, { x: margin + 10, y: y - 18, size: 10, font: fontBold });
    page.drawText(`Document Type: ${analysisResult.documentType} | Generated: ${new Date().toLocaleDateString('en-US')}`, { x: margin + 10, y: y - 35, size: 9, font: fontRegular });
    y -= 75;

    // ===== LETTER CONTENT – WORD-WRAPPED =====
    const text = letterHTML
      .replace(/<h[1-3]>/gi, '\n\n')
      .replace(/<\/h[1-3]>/gi, '\n')
      .replace(/<strong>/gi, '')
      .replace(/<\/strong>/gi, '')
      .replace(/<p>/gi, '')
      .replace(/<\/p>/gi, '\n\n')
      .replace(/<li>/gi, '• ')
      .replace(/<\/li>/gi, '\n')
      .replace(/<br\s*\/?>/gi, '\n')
      .trim();

    const paragraphs = text.split('\n');
    for (const para of paragraphs) {
      if (y < 100) break;
      const words = para.split(' ');
      let line = '', testLine;
      for (const w of words) {
        testLine = line + w + ' ';
        if (fontRegular.widthOfTextAtSize(testLine, 10) > maxWidth) {
          page.drawText(line.trim(), { x: margin, y, size: 10, font: fontRegular, color: rgb(0.1, 0.1, 0.1) });
          y -= 14;
          line = w + ' ';
        } else {
          line = testLine;
        }
      }
      if (line.trim()) {
        page.drawText(line.trim(), { x: margin, y, size: 10, font: fontRegular, color: rgb(0.1, 0.1, 0.1) });
        y -= 14;
      }
      y -= 6; // paragraph spacing
    }

    // ===== FOOTER =====
    page.drawText('Generated by Japa Genie AI | For official use only', { x: margin, y: 60, size: 8, font: fontRegular, color: rgb(0.5, 0.5, 0.5) });

    const pdfBytes = await pdfDoc.save();
    return new NextResponse(pdfBytes as any, {
      headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="Document-Report-${targetCountry}-${Date.now()}.pdf"` }
    });
  } catch (e: any) {
    return new NextResponse(JSON.stringify({ error: e.message }), { status: 500, headers: { 'Content-Type': 'application/json' } });
  }
}